// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pixelrun_Server;

#nullable disable

namespace Pixelrun_Server.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260422170849_INIT")]
    partial class INIT
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pixelrun_Server.Models.LevelRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Coins")
                        .HasColumnType("integer");

                    b.Property<int>("Kills")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("Time")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("LevelRecords");
                });

            modelBuilder.Entity("Pixelrun_Server.Models.OwnedSkin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("SkinId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SkinId");

                    b.ToTable("OwnedSkins");
                });

            modelBuilder.Entity("Pixelrun_Server.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Coins")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EquippedBarSkin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EquippedPlayerSkin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EquippedSlashSkin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Pixelrun_Server.Models.PlayerQuest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Claimed")
                        .HasColumnType("boolean");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<int>("CurrentValue")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("QuestId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("QuestId");

                    b.ToTable("PlayerQuests");
                });

            modelBuilder.Entity("Pixelrun_Server.Models.Quest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Reward")
                        .HasColumnType("integer");

                    b.Property<int>("TargetValue")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Quests");

                    b.HasData(
                        new
                        {
                            Id = "kills_5",
                            Description = "Kill 5 enemies",
                            Reward = 50,
                            TargetValue = 5,
                            Title = "First Blood",
                            Type = "kills"
                        },
                        new
                        {
                            Id = "kills_20",
                            Description = "Kill 20 enemies",
                            Reward = 150,
                            TargetValue = 20,
                            Title = "Hunter",
                            Type = "kills"
                        },
                        new
                        {
                            Id = "coins_10",
                            Description = "Collect 10 coins",
                            Reward = 30,
                            TargetValue = 10,
                            Title = "Collector",
                            Type = "coins"
                        },
                        new
                        {
                            Id = "coins_50",
                            Description = "Collect 50 coins",
                            Reward = 100,
                            TargetValue = 50,
                            Title = "Rich",
                            Type = "coins"
                        },
                        new
                        {
                            Id = "levels_1",
                            Description = "Complete 1 level",
                            Reward = 75,
                            TargetValue = 1,
                            Title = "First Level",
                            Type = "levels"
                        },
                        new
                        {
                            Id = "levels_5",
                            Description = "Complete 5 levels",
                            Reward = 300,
                            TargetValue = 5,
                            Title = "Veteran",
                            Type = "levels"
                        },
                        new
                        {
                            Id = "time_120",
                            Description = "Finish level < 2 min",
                            Reward = 200,
                            TargetValue = 120,
                            Title = "Speedrunner",
                            Type = "time"
                        });
                });

            modelBuilder.Entity("Pixelrun_Server.Models.Skin", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Skins");

                    b.HasData(
                        new
                        {
                            Id = "default",
                            Description = "Default skin",
                            Name = "Default",
                            Price = 0,
                            Type = "player"
                        },
                        new
                        {
                            Id = "ninja",
                            Description = "Fast ninja",
                            Name = "Ninja",
                            Price = 200,
                            Type = "player"
                        },
                        new
                        {
                            Id = "knight",
                            Description = "Heavy knight",
                            Name = "Knight",
                            Price = 350,
                            Type = "player"
                        },
                        new
                        {
                            Id = "ghost",
                            Description = "Ghost",
                            Name = "Ghost",
                            Price = 500,
                            Type = "player"
                        },
                        new
                        {
                            Id = "bar_default",
                            Description = "Default bar",
                            Name = "Default Bar",
                            Price = 0,
                            Type = "bar"
                        },
                        new
                        {
                            Id = "bar_fire",
                            Description = "Fire bar",
                            Name = "Fire Bar",
                            Price = 150,
                            Type = "bar"
                        },
                        new
                        {
                            Id = "bar_ice",
                            Description = "Ice bar",
                            Name = "Ice Bar",
                            Price = 150,
                            Type = "bar"
                        },
                        new
                        {
                            Id = "slash_default",
                            Description = "Default slash",
                            Name = "Default Slash",
                            Price = 0,
                            Type = "slash"
                        },
                        new
                        {
                            Id = "slash_fire",
                            Description = "Fire slash",
                            Name = "Fire Slash",
                            Price = 200,
                            Type = "slash"
                        },
                        new
                        {
                            Id = "slash_electric",
                            Description = "Electric slash",
                            Name = "Electric Slash",
                            Price = 250,
                            Type = "slash"
                        });
                });

            modelBuilder.Entity("Pixelrun_Server.Models.LevelRecord", b =>
                {
                    b.HasOne("Pixelrun_Server.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Pixelrun_Server.Models.OwnedSkin", b =>
                {
                    b.HasOne("Pixelrun_Server.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pixelrun_Server.Models.Skin", "Skin")
                        .WithMany()
                        .HasForeignKey("SkinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Skin");
                });

            modelBuilder.Entity("Pixelrun_Server.Models.PlayerQuest", b =>
                {
                    b.HasOne("Pixelrun_Server.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pixelrun_Server.Models.Quest", "Quest")
                        .WithMany()
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Quest");
                });
#pragma warning restore 612, 618
        }
    }
}
